services:
  postgres:
    image: postgres:16
    container_name: cuida-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cuida
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: cuida-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.cl
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  api:
    build: .
    container_name: cuida-api # Nombre que NO es el del servicio
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      # Espera a que la DB esté lista antes de iniciar la API
      postgres:
        condition: service_healthy


volumes:
  pgdata:
