FROM python:3.11-slim
# Instala las dependencias necesarias de la base de datos y la API
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# Copia el archivo de requisitos e instala las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código de la aplicación
COPY . .

# Comando de ejecución (aunque es sobrescrito por el docker-compose, es buena práctica tenerlo)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
