"""init

Revision ID: 6ec83827d62a
Revises: 
Create Date: 2025-10-02 17:14:39.616289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec83827d62a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuidador',
    sa.Column('rut_cuidador', sa.Integer(), nullable=False),
    sa.Column('primer_nombre_cuidador', sa.String(), nullable=False),
    sa.Column('segundo_nombre_cuidador', sa.String(), nullable=False),
    sa.Column('primer_apellido_cuidador', sa.String(), nullable=False),
    sa.Column('segundo_apellido_cuidador', sa.String(), nullable=False),
    sa.Column('sexo', sa.Boolean(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('rut_cuidador')
    )
    op.create_index(op.f('ix_cuidador_rut_cuidador'), 'cuidador', ['rut_cuidador'], unique=False)
    op.create_table('insignia',
    sa.Column('id_insignia', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre_insignia', sa.String(), nullable=False),
    sa.Column('descipcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_insignia')
    )
    op.create_index(op.f('ix_insignia_id_insignia'), 'insignia', ['id_insignia'], unique=False)
    op.create_table('region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre_region', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_region'),
    sa.UniqueConstraint('nombre_region')
    )
    op.create_index(op.f('ix_region_id_region'), 'region', ['id_region'], unique=False)
    op.create_table('unidad_medida',
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descipcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_unidad')
    )
    op.create_index(op.f('ix_unidad_medida_id_unidad'), 'unidad_medida', ['id_unidad'], unique=False)
    op.create_table('comuna',
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre_comuna', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['region.id_region'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_comuna'),
    sa.UniqueConstraint('nombre_comuna')
    )
    op.create_index(op.f('ix_comuna_id_comuna'), 'comuna', ['id_comuna'], unique=False)
    op.create_index(op.f('ix_comuna_id_region'), 'comuna', ['id_region'], unique=False)
    op.create_table('cuidador_historial',
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('rut_cuidador', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cambio', sa.String(), nullable=False),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rut_cuidador'], ['cuidador.rut_cuidador'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    op.create_index(op.f('ix_cuidador_historial_historial_id'), 'cuidador_historial', ['historial_id'], unique=False)
    op.create_index(op.f('ix_cuidador_historial_rut_cuidador'), 'cuidador_historial', ['rut_cuidador'], unique=False)
    op.create_table('medicina',
    sa.Column('id_medicina', sa.Integer(), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('instrucciones', sa.String(), nullable=False),
    sa.Column('toma_maxima', sa.String(), nullable=False),
    sa.Column('efectos', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad_medida.id_unidad'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_medicina')
    )
    op.create_index(op.f('ix_medicina_id_medicina'), 'medicina', ['id_medicina'], unique=False)
    op.create_index(op.f('ix_medicina_id_unidad'), 'medicina', ['id_unidad'], unique=False)
    op.create_table('parametro_clinico',
    sa.Column('id_parametro', sa.Integer(), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descipcion', sa.String(), nullable=False),
    sa.Column('rango_ref_min', sa.Integer(), nullable=False),
    sa.Column('rango_ref_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad_medida.id_unidad'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_parametro')
    )
    op.create_index(op.f('ix_parametro_clinico_id_parametro'), 'parametro_clinico', ['id_parametro'], unique=False)
    op.create_index(op.f('ix_parametro_clinico_id_unidad'), 'parametro_clinico', ['id_unidad'], unique=False)
    op.create_table('cesfam',
    sa.Column('id_cesfam', sa.Integer(), nullable=False),
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('nombre_cesfam', sa.String(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['comuna.id_comuna'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_cesfam')
    )
    op.create_index(op.f('ix_cesfam_id_cesfam'), 'cesfam', ['id_cesfam'], unique=False)
    op.create_index(op.f('ix_cesfam_id_comuna'), 'cesfam', ['id_comuna'], unique=False)
    op.create_table('equipo_medico',
    sa.Column('rut_medico', sa.Integer(), nullable=False),
    sa.Column('id_cesfam', sa.Integer(), nullable=False),
    sa.Column('primer_nombre_medico', sa.String(), nullable=False),
    sa.Column('segundo_nombre_medico', sa.String(), nullable=False),
    sa.Column('primer_apellido_medico', sa.String(), nullable=False),
    sa.Column('segundo_apellido_medico', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasenia', sa.String(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cesfam'], ['cesfam.id_cesfam'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rut_medico')
    )
    op.create_index(op.f('ix_equipo_medico_id_cesfam'), 'equipo_medico', ['id_cesfam'], unique=False)
    op.create_index(op.f('ix_equipo_medico_rut_medico'), 'equipo_medico', ['rut_medico'], unique=False)
    op.create_table('paciente',
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('primer_nombre_paciente', sa.String(), nullable=False),
    sa.Column('segundo_nombre_paciente', sa.String(), nullable=False),
    sa.Column('primer_apellido_paciente', sa.String(), nullable=False),
    sa.Column('segundo_apellido_paciente', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sexo', sa.Boolean(), nullable=False),
    sa.Column('tipo_de_sangre', sa.String(), nullable=False),
    sa.Column('enfermedades', sa.String(), nullable=False),
    sa.Column('seguro', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('tipo_paciente', sa.String(), nullable=False),
    sa.Column('nombre_contacto', sa.String(), nullable=False),
    sa.Column('telefono_contacto', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_cesfam', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio_cesfam', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin_cesfam', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo_cesfam', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cesfam'], ['cesfam.id_cesfam'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_comuna'], ['comuna.id_comuna'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rut_paciente')
    )
    op.create_index(op.f('ix_paciente_id_cesfam'), 'paciente', ['id_cesfam'], unique=False)
    op.create_index(op.f('ix_paciente_id_comuna'), 'paciente', ['id_comuna'], unique=False)
    op.create_index(op.f('ix_paciente_rut_paciente'), 'paciente', ['rut_paciente'], unique=False)
    op.create_table('evento_gamificacion',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index(op.f('ix_evento_gamificacion_id_evento'), 'evento_gamificacion', ['id_evento'], unique=False)
    op.create_index(op.f('ix_evento_gamificacion_rut_paciente'), 'evento_gamificacion', ['rut_paciente'], unique=False)
    op.create_table('gamificacion_perfil',
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('racha_dias', sa.Integer(), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rut_paciente')
    )
    op.create_index(op.f('ix_gamificacion_perfil_rut_paciente'), 'gamificacion_perfil', ['rut_paciente'], unique=False)
    op.create_table('medicina_detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_medicina', sa.Integer(), nullable=False),
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('dosis', sa.String(), nullable=False),
    sa.Column('instrucciones_toma', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tomada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicina'], ['medicina.id_medicina'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_medicina_detalle_id_detalle'), 'medicina_detalle', ['id_detalle'], unique=False)
    op.create_index(op.f('ix_medicina_detalle_id_medicina'), 'medicina_detalle', ['id_medicina'], unique=False)
    op.create_index(op.f('ix_medicina_detalle_rut_paciente'), 'medicina_detalle', ['rut_paciente'], unique=False)
    op.create_table('medicion',
    sa.Column('id_medicion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('registrado_por', sa.String(), nullable=False),
    sa.Column('observacion', sa.String(), nullable=False),
    sa.Column('evaluada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tiene_alerta', sa.Boolean(), nullable=False),
    sa.Column('severidad_max', sa.String(), nullable=False),
    sa.Column('resumen_alerta', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_medicion')
    )
    op.create_index(op.f('ix_medicion_id_medicion'), 'medicion', ['id_medicion'], unique=False)
    op.create_index(op.f('ix_medicion_rut_paciente'), 'medicion', ['rut_paciente'], unique=False)
    op.create_table('medico_historial',
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('rut_medico', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cambio', sa.String(), nullable=False),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rut_medico'], ['equipo_medico.rut_medico'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    op.create_index(op.f('ix_medico_historial_historial_id'), 'medico_historial', ['historial_id'], unique=False)
    op.create_index(op.f('ix_medico_historial_rut_medico'), 'medico_historial', ['rut_medico'], unique=False)
    op.create_table('nota_clinica',
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('rut_medico', sa.Integer(), nullable=False),
    sa.Column('tipo_autor', sa.String(), nullable=False),
    sa.Column('nota', sa.String(), nullable=False),
    sa.Column('tipo_nota', sa.String(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rut_medico'], ['equipo_medico.rut_medico'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_nota')
    )
    op.create_index(op.f('ix_nota_clinica_id_nota'), 'nota_clinica', ['id_nota'], unique=False)
    op.create_index(op.f('ix_nota_clinica_rut_medico'), 'nota_clinica', ['rut_medico'], unique=False)
    op.create_index(op.f('ix_nota_clinica_rut_paciente'), 'nota_clinica', ['rut_paciente'], unique=False)
    op.create_table('paciente_cuidador',
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('rut_cuidador', sa.Integer(), nullable=False),
    sa.Column('permiso_registro', sa.Boolean(), nullable=False),
    sa.Column('permiso_lectura', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rut_cuidador'], ['cuidador.rut_cuidador'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rut_paciente', 'rut_cuidador')
    )
    op.create_index(op.f('ix_paciente_cuidador_rut_cuidador'), 'paciente_cuidador', ['rut_cuidador'], unique=False)
    op.create_index(op.f('ix_paciente_cuidador_rut_paciente'), 'paciente_cuidador', ['rut_paciente'], unique=False)
    op.create_table('paciente_historial',
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cambio', sa.String(), nullable=False),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    op.create_index(op.f('ix_paciente_historial_historial_id'), 'paciente_historial', ['historial_id'], unique=False)
    op.create_index(op.f('ix_paciente_historial_rut_paciente'), 'paciente_historial', ['rut_paciente'], unique=False)
    op.create_table('rango_paciente',
    sa.Column('id_rango', sa.Integer(), nullable=False),
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('id_parametro', sa.Integer(), nullable=False),
    sa.Column('min_normal', sa.Integer(), nullable=False),
    sa.Column('max_normal', sa.Integer(), nullable=False),
    sa.Column('min_critico', sa.Integer(), nullable=False),
    sa.Column('max_critico', sa.Integer(), nullable=False),
    sa.Column('vigencia_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigencia_hasta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definido_por', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_parametro'], ['parametro_clinico.id_parametro'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rango')
    )
    op.create_index(op.f('ix_rango_paciente_id_parametro'), 'rango_paciente', ['id_parametro'], unique=False)
    op.create_index(op.f('ix_rango_paciente_id_rango'), 'rango_paciente', ['id_rango'], unique=False)
    op.create_index(op.f('ix_rango_paciente_rut_paciente'), 'rango_paciente', ['rut_paciente'], unique=False)
    op.create_table('solicitud_reporte',
    sa.Column('id_reporte', sa.Integer(), nullable=False),
    sa.Column('rut_medico', sa.Integer(), nullable=False),
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('rango_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rango_hasta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rut_medico'], ['equipo_medico.rut_medico'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    op.create_index(op.f('ix_solicitud_reporte_id_reporte'), 'solicitud_reporte', ['id_reporte'], unique=False)
    op.create_index(op.f('ix_solicitud_reporte_rut_medico'), 'solicitud_reporte', ['rut_medico'], unique=False)
    op.create_index(op.f('ix_solicitud_reporte_rut_paciente'), 'solicitud_reporte', ['rut_paciente'], unique=False)
    op.create_table('usuario_insignia',
    sa.Column('rut_paciente', sa.Integer(), nullable=False),
    sa.Column('id_insignia', sa.Integer(), nullable=False),
    sa.Column('otorgada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_insignia'], ['insignia.id_insignia'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rut_paciente'], ['paciente.rut_paciente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rut_paciente', 'id_insignia')
    )
    op.create_index(op.f('ix_usuario_insignia_id_insignia'), 'usuario_insignia', ['id_insignia'], unique=False)
    op.create_index(op.f('ix_usuario_insignia_rut_paciente'), 'usuario_insignia', ['rut_paciente'], unique=False)
    op.create_table('descarga_reporte',
    sa.Column('id_descarga', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut_medico', sa.Integer(), nullable=False),
    sa.Column('id_reporte', sa.Integer(), nullable=False),
    sa.Column('descargado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_reporte'], ['solicitud_reporte.id_reporte'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rut_medico'], ['equipo_medico.rut_medico'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_descarga')
    )
    op.create_index(op.f('ix_descarga_reporte_id_descarga'), 'descarga_reporte', ['id_descarga'], unique=False)
    op.create_index(op.f('ix_descarga_reporte_id_reporte'), 'descarga_reporte', ['id_reporte'], unique=False)
    op.create_index(op.f('ix_descarga_reporte_rut_medico'), 'descarga_reporte', ['rut_medico'], unique=False)
    op.create_table('medicion_detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_medicion', sa.Integer(), nullable=False),
    sa.Column('id_parametro', sa.Integer(), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('valor_num', sa.Integer(), nullable=False),
    sa.Column('valor_texto', sa.String(), nullable=False),
    sa.Column('fuera_rango', sa.Boolean(), nullable=False),
    sa.Column('severidad', sa.String(), nullable=False),
    sa.Column('umbral_min', sa.Integer(), nullable=False),
    sa.Column('umbral_max', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicion'], ['medicion.id_medicion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_parametro'], ['parametro_clinico.id_parametro'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad_medida.id_unidad'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_medicion_detalle_id_detalle'), 'medicion_detalle', ['id_detalle'], unique=False)
    op.create_index(op.f('ix_medicion_detalle_id_medicion'), 'medicion_detalle', ['id_medicion'], unique=False)
    op.create_index(op.f('ix_medicion_detalle_id_parametro'), 'medicion_detalle', ['id_parametro'], unique=False)
    op.create_index(op.f('ix_medicion_detalle_id_unidad'), 'medicion_detalle', ['id_unidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicion_detalle_id_unidad'), table_name='medicion_detalle')
    op.drop_index(op.f('ix_medicion_detalle_id_parametro'), table_name='medicion_detalle')
    op.drop_index(op.f('ix_medicion_detalle_id_medicion'), table_name='medicion_detalle')
    op.drop_index(op.f('ix_medicion_detalle_id_detalle'), table_name='medicion_detalle')
    op.drop_table('medicion_detalle')
    op.drop_index(op.f('ix_descarga_reporte_rut_medico'), table_name='descarga_reporte')
    op.drop_index(op.f('ix_descarga_reporte_id_reporte'), table_name='descarga_reporte')
    op.drop_index(op.f('ix_descarga_reporte_id_descarga'), table_name='descarga_reporte')
    op.drop_table('descarga_reporte')
    op.drop_index(op.f('ix_usuario_insignia_rut_paciente'), table_name='usuario_insignia')
    op.drop_index(op.f('ix_usuario_insignia_id_insignia'), table_name='usuario_insignia')
    op.drop_table('usuario_insignia')
    op.drop_index(op.f('ix_solicitud_reporte_rut_paciente'), table_name='solicitud_reporte')
    op.drop_index(op.f('ix_solicitud_reporte_rut_medico'), table_name='solicitud_reporte')
    op.drop_index(op.f('ix_solicitud_reporte_id_reporte'), table_name='solicitud_reporte')
    op.drop_table('solicitud_reporte')
    op.drop_index(op.f('ix_rango_paciente_rut_paciente'), table_name='rango_paciente')
    op.drop_index(op.f('ix_rango_paciente_id_rango'), table_name='rango_paciente')
    op.drop_index(op.f('ix_rango_paciente_id_parametro'), table_name='rango_paciente')
    op.drop_table('rango_paciente')
    op.drop_index(op.f('ix_paciente_historial_rut_paciente'), table_name='paciente_historial')
    op.drop_index(op.f('ix_paciente_historial_historial_id'), table_name='paciente_historial')
    op.drop_table('paciente_historial')
    op.drop_index(op.f('ix_paciente_cuidador_rut_paciente'), table_name='paciente_cuidador')
    op.drop_index(op.f('ix_paciente_cuidador_rut_cuidador'), table_name='paciente_cuidador')
    op.drop_table('paciente_cuidador')
    op.drop_index(op.f('ix_nota_clinica_rut_paciente'), table_name='nota_clinica')
    op.drop_index(op.f('ix_nota_clinica_rut_medico'), table_name='nota_clinica')
    op.drop_index(op.f('ix_nota_clinica_id_nota'), table_name='nota_clinica')
    op.drop_table('nota_clinica')
    op.drop_index(op.f('ix_medico_historial_rut_medico'), table_name='medico_historial')
    op.drop_index(op.f('ix_medico_historial_historial_id'), table_name='medico_historial')
    op.drop_table('medico_historial')
    op.drop_index(op.f('ix_medicion_rut_paciente'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_id_medicion'), table_name='medicion')
    op.drop_table('medicion')
    op.drop_index(op.f('ix_medicina_detalle_rut_paciente'), table_name='medicina_detalle')
    op.drop_index(op.f('ix_medicina_detalle_id_medicina'), table_name='medicina_detalle')
    op.drop_index(op.f('ix_medicina_detalle_id_detalle'), table_name='medicina_detalle')
    op.drop_table('medicina_detalle')
    op.drop_index(op.f('ix_gamificacion_perfil_rut_paciente'), table_name='gamificacion_perfil')
    op.drop_table('gamificacion_perfil')
    op.drop_index(op.f('ix_evento_gamificacion_rut_paciente'), table_name='evento_gamificacion')
    op.drop_index(op.f('ix_evento_gamificacion_id_evento'), table_name='evento_gamificacion')
    op.drop_table('evento_gamificacion')
    op.drop_index(op.f('ix_paciente_rut_paciente'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_id_comuna'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_id_cesfam'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_equipo_medico_rut_medico'), table_name='equipo_medico')
    op.drop_index(op.f('ix_equipo_medico_id_cesfam'), table_name='equipo_medico')
    op.drop_table('equipo_medico')
    op.drop_index(op.f('ix_cesfam_id_comuna'), table_name='cesfam')
    op.drop_index(op.f('ix_cesfam_id_cesfam'), table_name='cesfam')
    op.drop_table('cesfam')
    op.drop_index(op.f('ix_parametro_clinico_id_unidad'), table_name='parametro_clinico')
    op.drop_index(op.f('ix_parametro_clinico_id_parametro'), table_name='parametro_clinico')
    op.drop_table('parametro_clinico')
    op.drop_index(op.f('ix_medicina_id_unidad'), table_name='medicina')
    op.drop_index(op.f('ix_medicina_id_medicina'), table_name='medicina')
    op.drop_table('medicina')
    op.drop_index(op.f('ix_cuidador_historial_rut_cuidador'), table_name='cuidador_historial')
    op.drop_index(op.f('ix_cuidador_historial_historial_id'), table_name='cuidador_historial')
    op.drop_table('cuidador_historial')
    op.drop_index(op.f('ix_comuna_id_region'), table_name='comuna')
    op.drop_index(op.f('ix_comuna_id_comuna'), table_name='comuna')
    op.drop_table('comuna')
    op.drop_index(op.f('ix_unidad_medida_id_unidad'), table_name='unidad_medida')
    op.drop_table('unidad_medida')
    op.drop_index(op.f('ix_region_id_region'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_insignia_id_insignia'), table_name='insignia')
    op.drop_table('insignia')
    op.drop_index(op.f('ix_cuidador_rut_cuidador'), table_name='cuidador')
    op.drop_table('cuidador')
    # ### end Alembic commands ###
