from .region import Region
from .comuna import Comuna
from .cesfam import Cesfam
from .paciente import Paciente
from .equipo_medico import EquipoMedico
from .cuidador import Cuidador
from .paciente_cuidador import PacienteCuidador
from .cuidador_historial import CuidadorHistorial
from .paciente_historial import PacienteHistorial
from .medico_historial import MedicoHistorial
from .gamificacion_perfil import GamificacionPerfil
from .evento_gamificacion import EventoGamificacion
from .insignia import Insignia
from .usuario_insignia import UsuarioInsignia
from .unidad_medida import UnidadMedida
from .parametro_clinico import ParametroClinico
from .rango_paciente import RangoPaciente
from .solicitud_reporte import SolicitudReporte
from .descarga_reporte import DescargaReporte
from .nota_clinica import NotaClinica
from .medicion import Medicion
from .medicion_detalle import MedicionDetalle
from .medicina import Medicina
from .medicina_detalle import MedicinaDetalle
from .tarea import Tarea
from .notificaciones import Notificacion
from .preferencia_notificaciones import PreferenciaNotificacion